// @vitest-environment node
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";

import { runBuild } from "../../src/cli/build";
import {
  conventionConfig,
  formatConfigFile,
  isConventionConfig,
  loadConfig,
  writeConfigFile,
} from "../../src/cli/config";
import { hasTokensImport, injectTokensImport } from "../../src/cli/inject";
import { runInit } from "../../src/cli/init";
import {
  defaultThemeDir,
  findStylesheetCandidates,
  relativeImportPath,
} from "../../src/cli/paths";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

const tempDirs: string[] = [];

function makeTempProject(options?: {
  withSrc?: boolean;
  stylesheets?: string[];
}): string {
  const dir = mkdtempSync(join(tmpdir(), "design-tokens-cli-"));
  tempDirs.push(dir);
  writeFileSync(
    join(dir, "package.json"),
    JSON.stringify({ name: "temp-app", type: "module" }),
  );

  mkdirSync(join(dir, "node_modules"), { recursive: true });
  symlinkSync(packageRoot, join(dir, "node_modules", "design-token"), "dir");

  if (options?.withSrc) {
    mkdirSync(join(dir, "src"), { recursive: true });
  }

  for (const sheet of options?.stylesheets ?? []) {
    const abs = join(dir, sheet);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, "/* app styles */\n", "utf8");
  }

  return dir;
}

afterEach(() => {
  while (tempDirs.length > 0) {
    const dir = tempDirs.pop();
    if (dir) rmSync(dir, { recursive: true, force: true });
  }
});

describe("paths", () => {
  it("uses src/theme when src exists", () => {
    const root = makeTempProject({ withSrc: true });
    expect(defaultThemeDir(root)).toBe("src/theme");
    expect(conventionConfig(root).tokens.file).toBe("src/theme/tokens.ts");
  });

  it("uses theme when src is absent", () => {
    const root = makeTempProject();
    expect(defaultThemeDir(root)).toBe("theme");
    expect(conventionConfig(root).output.css).toBe("theme/tokens.css");
  });

  it("finds all stylesheet candidates in search order", () => {
    const root = makeTempProject({
      withSrc: true,
      stylesheets: ["src/index.css", "src/app/globals.css", "styles/globals.css"],
    });
    expect(findStylesheetCandidates(root)).toEqual([
      "src/app/globals.css",
      "src/index.css",
      "styles/globals.css",
    ]);
  });

  it("computes relative CSS import paths", () => {
    expect(
      relativeImportPath(
        "/app/src/app/globals.css",
        "/app/src/theme/tokens.css",
      ),
    ).toBe("../theme/tokens.css");
  });
});

describe("inject", () => {
  it("adds import once and is idempotent", () => {
    const root = makeTempProject({
      withSrc: true,
      stylesheets: ["src/app/globals.css"],
    });
    const sheet = join(root, "src/app/globals.css");
    const css = join(root, "src/theme/tokens.css");
    mkdirSync(dirname(css), { recursive: true });
    writeFileSync(css, "/* tokens */\n");

    const first = injectTokensImport(sheet, css);
    expect(first.status).toBe("added");
    expect(readFileSync(sheet, "utf8")).toContain(
      '@import "../theme/tokens.css";',
    );

    const second = injectTokensImport(sheet, css);
    expect(second.status).toBe("exists");
    expect(
      readFileSync(sheet, "utf8").match(/@import/g)?.length,
    ).toBe(1);
    expect(hasTokensImport(sheet, css)).toBe(true);
  });
});

describe("init", () => {
  it("scaffolds convention files and injects stylesheet with -y", async () => {
    const root = makeTempProject({
      withSrc: true,
      stylesheets: ["src/app/globals.css"],
    });

    await runInit({ yes: true, cwd: root });

    expect(existsSync(join(root, "src/theme/tokens.ts"))).toBe(true);
    expect(existsSync(join(root, "src/theme/tokens.css"))).toBe(true);
    expect(existsSync(join(root, "design-tokens.config.ts"))).toBe(false);
    expect(readFileSync(join(root, "src/app/globals.css"), "utf8")).toContain(
      '@import "../theme/tokens.css";',
    );
    expect(readFileSync(join(root, "src/theme/tokens.css"), "utf8")).toContain(
      "AUTO-GENERATED BY design-token",
    );
    expect(readFileSync(join(root, "src/theme/tokens.css"), "utf8")).toContain(
      ":root{",
    );
  });

  it("does not overwrite existing tokens.ts", async () => {
    const root = makeTempProject({ withSrc: true });
    const tokensPath = join(root, "src/theme/tokens.ts");
    mkdirSync(dirname(tokensPath), { recursive: true });
    const marker = "// keep-me\nexport const tokens = { css: () => ':root{}' };\n";
    writeFileSync(tokensPath, marker, "utf8");

    await runInit({ yes: true, cwd: root });

    expect(readFileSync(tokensPath, "utf8")).toBe(marker);
  });

  it("writes config for custom paths and build reads it", async () => {
    const root = makeTempProject({ withSrc: true });
    const customTokens = join(root, "src/design-system/theme.ts");
    mkdirSync(dirname(customTokens), { recursive: true });
    writeFileSync(
      customTokens,
      `import { defineTokens } from "design-token";
export const theme = defineTokens({
  defaultTheme: "light",
  themes: {
    light: { selector: ":root", tokens: { accent: "red" } },
  },
});
`,
      "utf8",
    );

    const config = {
      tokens: { file: "./src/design-system/theme.ts", export: "theme" },
      output: { css: "./src/design-system/variables.css" },
    };
    writeConfigFile(root, config);
    expect(isConventionConfig(root, config)).toBe(false);

    const { outputPath } = await runBuild(root);
    expect(outputPath).toBe(join(root, "src/design-system/variables.css"));
    expect(readFileSync(outputPath, "utf8")).toContain("--accent:red");
    expect(readFileSync(customTokens, "utf8")).toContain("export const theme");
  });
});

describe("build", () => {
  it("regenerates CSS without changing tokens.ts", async () => {
    const root = makeTempProject({ withSrc: true });
    const tokensPath = join(root, "src/theme/tokens.ts");
    mkdirSync(dirname(tokensPath), { recursive: true });
    const source = `import { defineTokens } from "design-token";
export const tokens = defineTokens({
  defaultTheme: "light",
  themes: {
    light: { selector: ":root", tokens: { brand: "blue" } },
  },
});
`;
    writeFileSync(tokensPath, source, "utf8");
    writeFileSync(join(root, "src/theme/tokens.css"), "/* stale */\n", "utf8");

    await runBuild(root);

    expect(readFileSync(tokensPath, "utf8")).toBe(source);
    const css = readFileSync(join(root, "src/theme/tokens.css"), "utf8");
    expect(css).toContain("--brand:blue");
    expect(css).not.toContain("stale");
  });
});

describe("config", () => {
  it("loadConfig falls back to conventions", async () => {
    const root = makeTempProject({ withSrc: true });
    const loaded = await loadConfig(root);
    expect(loaded.tokens.file).toBe("src/theme/tokens.ts");
    expect(loaded.configPath).toBeNull();
  });

  it("formatConfigFile includes inject when set", () => {
    const text = formatConfigFile({
      tokens: { file: "./a.ts", export: "tokens" },
      output: { css: "./b.css" },
      inject: { css: "./c.css" },
    });
    expect(text).toContain('css: "./c.css"');
  });
});
