import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

export const PACKAGE_BANNER_NAME = "design-token";

export function formatGeneratedCss(
  cssBody: string,
  packageName: string = PACKAGE_BANNER_NAME,
): string {
  return `/**
 * AUTO-GENERATED BY ${packageName}.
 * DO NOT EDIT MANUALLY.
 */

${cssBody}
`;
}

export function writeCssFile(
  outputPath: string,
  cssBody: string,
  packageName: string = PACKAGE_BANNER_NAME,
): void {
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, formatGeneratedCss(cssBody, packageName), "utf8");
}
