import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

export const PACKAGE_BANNER_NAME = "design-token-package";

export function formatGeneratedCss(
  cssBody: string,
  packageName: string = PACKAGE_BANNER_NAME,
  themeBlock?: string,
): string {
  const parts = [
    `/**
 * AUTO-GENERATED BY ${packageName}.
 * DO NOT EDIT MANUALLY.
 */

${cssBody.trim()}`,
  ];

  if (themeBlock?.trim()) {
    parts.push("", themeBlock.trim());
  }

  return `${parts.join("\n")}\n`;
}

export function writeCssFile(
  outputPath: string,
  cssBody: string,
  options?: {
    packageName?: string;
    themeBlock?: string;
  },
): void {
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(
    outputPath,
    formatGeneratedCss(
      cssBody,
      options?.packageName ?? PACKAGE_BANNER_NAME,
      options?.themeBlock,
    ),
    "utf8",
  );
}
