export function tokensScaffold(packageName: string): string {
  return `import { defineTokens } from "${packageName}";

export const tokens = defineTokens({
  defaultTheme: "light",
  themes: {
    light: {
      selector: ":root",
      tokens: {
        background: "oklch(1 0 0)",
        foreground: "oklch(0.145 0 0)",
        primary: "oklch(0% 0 0)",
        radius: "0.625rem",
      },
    },
    dark: {
      selector: ".dark",
      tokens: {
        background: "oklch(0% 0 0)",
        foreground: "oklch(1 0 0)",
        primary: "oklch(1 0 0)",
        radius: "0.625rem",
      },
    },
  },
});
`;
}

export function emptyCssStub(): string {
  return `/*
 * Design tokens CSS — generated by \`npx design-tokens build\`.
 *
 * 1. Define tokens in your tokens.ts file
 * 2. Run: npx design-tokens build
 * 3. Import this file in your main stylesheet
 *
 * Do not edit by hand; re-run build after changing tokens.
 */
`;
}
